siteRepos:
  - gratka:
      "baseUrlStr": "https://gratka.pl"
      "urlSearchContext": "nieruchomosci/mieszkania?cena-calkowita:min=600000000"
database:
  fileName: ~/.offertracker/offertracker
